### PR TITLE
Register parent types before children types

### LINKED ISSUE #24: Source generator may attempt to register child class before parent class
### Godot version

4.3.stable.nixpkgs.77dcf97d8

### Godot .NET packages version

6bd7581

### System information

NixOS 24.11

### .NET information

9.0.100-rc.1.24452.12

### Issue description

When using the source generator and inheriting from a [GodotClass] the source generator registers classes in an arbitrary order which may lead to child classes being registered before their parents and therefore failing to become registered into ClassDB

### Steps to reproduce

Create a parent class annotated with [GodotClass]
Create a child class that inherits from the parent class annotated with [GodotClass]
Main.generated.cs may place the parent class after the child class which will fail

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ArchercatNEO**
Fixes #24

### CODE REVIEW

File: src/Godot.SourceGenerators/EntryPointGenerator.cs [hunk 1]
```diff
@@ -25,12 +27,56 @@ public void Initialize(IncrementalGeneratorInitializationContext context)
...
+                    }
+
+                    if (dependencyTree.ContainsKey(parent))
+                    {
+                        dependencyTree[parent] += dependencies;
+                    }
+                    else
+                    {
+                        dependencyTree.Add(parent, dependencies);
+                    }
```
Comment (raulsntos) [inline src/Godot.SourceGenerators/EntryPointGenerator.cs:72]: Since we always end up assigning to the dictionary, we could reduce it to this:

```suggestion
                    derivedTypeCountByBaseTypeName.TryGetValue(baseTypeName, out int oldDerivedTypeCount);
                    derivedTypeCountByBaseTypeName[baseTypeName] = oldDerivedTypeCount + derivedTypeCount;
```

Although I'm not sure it's better.

File: src/Godot.SourceGenerators/SpecCollectors/RegistrationSpecCollector.cs [hunk 2]
```diff
@@ -15,6 +15,12 @@ internal static class RegistrationSpecCollector
             return null;
         }
 
+        if (typeSymbol.BaseType is null)
+        {
+            // Attribute has been placed on an interface.
+            return null;
+        }
```
Comment (raulsntos) [inline src/Godot.SourceGenerators/SpecCollectors/RegistrationSpecCollector.cs:22]: This should not be possible, the attribute is only valid on 'class' declarations:

https://github.com/raulsntos/godot-dotnet/blob/6bd7581727ca2e4b6e82e6775060d874215313ce/src/Godot.Bindings/Core/Attributes/GodotClassAttribute.cs#L8-L9

**Review by raulsntos — COMMENTED** [review]
Thank you so much for the contribution, and sorry for the delay in reviewing.

Could you also add tests to `Godot.SourceGenerators.Tests` to ensure the generator registers the classes in the expected order? Ideally a test that failed before this PR to validate that this PR fixes it.

File: tests/Godot.SourceGenerators.Tests/TestData/Sources/NodesWithInheritance.cs
Comment (raulsntos) [inline tests/Godot.SourceGenerators.Tests/TestData/Sources/NodesWithInheritance.cs:1]: Reorder the types so the derived types come first, that way we make sure the changes to the generator are actually sorting the types and don't just happen to take them in the same order they are declared.

**Review by raulsntos — APPROVED** [review]
Thanks, looks good to me :+1: 

Also, since you are a new contributor, make sure to read [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md) and the [contributing documentation](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html) if you haven't already.

You'll need to squash the commits before this PR can be merged. The [contributing documentation](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) contains information about squashing in case you need it.

Feel free to reach out in the [development chat](https://chat.godotengine.org) if you need help.

**Comment by raulsntos** [comment]
Thanks!
